# Generated by Django 3.1 on 2020-09-20 13:02

from django.db import migrations, models
import django.db.models.deletion
import kartu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamaSekolah',
            fields=[
                ('nama', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekolahnama', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ShowPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='foto')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='kartu.show')),
            ],
        ),
        migrations.CreateModel(
            name='DesainKartu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kartudepan', models.ImageField(blank=True, null=True, upload_to=kartu.models.get_upload_path)),
                ('kartubelakang', models.ImageField(blank=True, null=True, upload_to=kartu.models.get_upload_path)),
                ('sekolah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kartu.namasekolah')),
            ],
        ),
        migrations.CreateModel(
            name='DataMurid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=30, null=True)),
                ('IdCard', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Pada Kartu')),
                ('alamat', models.CharField(blank=True, max_length=30, null=True)),
                ('TempatLahir', models.CharField(blank=True, max_length=30, null=True)),
                ('TanggalLahir', models.CharField(blank=True, max_length=30, null=True)),
                ('IdImage', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID untuk get image')),
                ('TTL', models.CharField(blank=True, max_length=50, null=True)),
                ('other', models.CharField(blank=True, max_length=50, null=True)),
                ('other2', models.CharField(blank=True, max_length=50, null=True)),
                ('sekolah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kartu.namasekolah')),
            ],
        ),
    ]
