# Generated by Django 3.1 on 2020-09-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamurid',
            name='other2',
        ),
    ]
