# Generated by Django 3.1 on 2020-09-20 13:13

from django.db import migrations, models
import kartu.models


class Migration(migrations.Migration):

    dependencies = [
        ('kartu', '0002_remove_datamurid_other2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showphoto',
            name='photo',
            field=models.ImageField(upload_to=kartu.models.get_upload_path_foto),
        ),
    ]
