# Generated by Django 3.1 on 2020-09-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartu', '0003_auto_20200920_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamurid',
            name='kategori',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sd/smp/sma'),
        ),
        migrations.AddField(
            model_name='desainkartu',
            name='kategori',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='sd/smp/sma'),
        ),
    ]
