# Generated by Django 3.1 on 2020-09-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartu', '0004_auto_20200924_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamurid',
            name='fotoExtension',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
