# Generated by Django 3.1 on 2020-10-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartu', '0005_datamurid_fotoextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamurid',
            name='cetak',
            field=models.BooleanField(default=False),
        ),
    ]
